### ISSUE TITLE
上架到小米市场了吗，我刚看到小米市场里边也有一个

### ISSUE THREAD

**Issue by zzzsssbo** [goweii/WanAndroid#13]

**Comment by goweii** [comment]
没有上架小米，只上架了酷安。

**Comment by zhangshaobo87** [comment]
那你的app被别人给上架到小米市场了，里边登录页面中你的名字都没改

**Comment by fddlpz** [comment]
签名被改了，是一个公司上架的

**Comment by zhangshaobo87** [comment]
是的

**Comment by goweii** [comment]
刚看了下，applicationid都没换。
但是包变大了2mb，不清楚加了什么进去，你们不要下载。

**Comment by zhangshaobo87** [comment]
你可以去投诉啊

**Comment by goweii** [comment]
点举报了，还没回复

**Comment by luckylicy** [comment]
刚才用模拟器看了一下， 被改成博彩网站了，做了一个马甲包
![微信图片_20191010113520](https://user-images.githubusercontent.com/38743524/66537146-109bc380-eb52-11e9-89a2-02cc8f8b3450.png)

**Comment by goweii** [comment]
嗯我看到了，咨询小米后，说是让提交侵权投诉通知书，里面需要软著或其他证明文件，但是因为APP是开源的，大概率通过不了，所以暂时没有提交。你们不要下载就好，以免造成损失。

**Comment by zhangshaobo87** [comment]
小米就是这样  投诉很难起作用

**Comment by zhangshaobo87** [comment]
我上次在小米市场看到好几个违规的app 举报根本不管

**Comment by jaydroid1024** [comment]
![image](https://user-images.githubusercontent.com/18594480/100957986-6ef5e380-3556-11eb-9278-a8dae8f7f41b.png)

**Comment by jaydroid1024** [comment]
这个就是后遗症吧

**Comment by goweii** [comment]
嗯，是这个后遗症，现在已经禁止申诉了，被拉黑名单了。
