### ISSUE TITLE
您好，我试图把你的项目升级到Androidx，好多报错，有时间去升级一下androidx吗

### ISSUE THREAD

**Issue by guiyanbing** [goweii/WanAndroid#14]
您好，我试图把你的项目升级到Androidx，好多报错，有时间去升级一下androidx吗

**Comment by goweii** [comment]
项目里很多框架都用的支持appcompat的，迁移比较麻烦。而且个人感觉就mvp架构androidx并没有太大优势。以后有时间可能会直接用kotlin+mvvm+androidx重写一遍。暂时不考虑，太忙了。

**Comment by guiyanbing** [comment]
我试了一下升级成功了，一键切换后改了glide和butterknife的配置，现在可以正常运行了，谢谢作者，封装的挺好
