### ISSUE TITLE
图片上传库有两个问题

### ISSUE THREAD

**Issue by JerryAlexLiang** [goweii/WanAndroid#16]
1、PictureSelector封装的工具类如果自定义压缩or拍照路径，会crash
2、在默认打开的“相机胶卷”滑动一屏，再打开其它相册如“Screenshots”，打开的列表不会滚动到顶部。

**Comment by goweii** [comment]
PictureSelector这个库是一个第三方，在wanandroid中只是一个小功能。你说的这两个问题我可能不会去修复，毕竟精力有限。而且PictureSelector库个人感觉繁琐臃肿，代码不够清晰，不建议使用。有一个知乎开源的感觉还可以，或者直接上原生的。

**Comment by JerryAlexLiang** [comment]
好的，谢谢。




------------------ 原始邮件 ------------------
发件人: "Goweii"<notifications@github.com>;
发送时间: 2019年9月18日(星期三) 中午1:59
收件人: "goweii/WanAndroid"<WanAndroid@noreply.github.com>;
抄送: "晚风轻轻-遮住的岁月Jerry"<1935990239@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [goweii/WanAndroid] 图片上传库有两个问题 (#16)




PictureSelector这个库是一个第三方，在wanandroid中只是一个小功能。你说的这两个问题我可能不会去修复，毕竟精力有限。而且PictureSelector库个人感觉繁琐臃肿，代码不够清晰，不建议使用。有一个知乎开源的感觉还可以，或者直接上原生的。
