### ISSUE TITLE
内嵌浏览器问题

### ISSUE THREAD

**Issue by wcedla** [goweii/WanAndroid#17]
打开的很多文章图片都显示不出来，特别是gif动图，还有就是当前最新版本的关于作者打开白屏，手机是lgg5 8.0系统

**Comment by goweii** [comment]
文章图片不显示的可以切换拦截模式试下。
关于作者可能接口失效了，周末处理。

**Comment by goweii** [comment]
因更新，建议卸载重新安装试下。

**Comment by goweii** [comment]
已更新x5内核，更新1.3.1版本试下
