### ISSUE TITLE
错误: 找不到符号 符号:   类 Blurred 位置: 程序包 per.goweii.burred	

### ISSUE THREAD

**Issue by fenghongjian** [goweii/WanAndroid#2]
“  import per.goweii.burred.Blurred; ”未使用
错误: 找不到符号
符号:   类 Blurred
位置: 程序包 per.goweii.burred
![bug](https://user-images.githubusercontent.com/46391287/58598122-855e1780-82ad-11e9-876f-32969cc61365.PNG)

**Comment by goweii** [comment]
已修复
