### ISSUE TITLE
项目编译不过： Could not resolve io.realm:realm-gradle-plugin:5.12.0-SNAPSHOT.

### ISSUE THREAD

**Issue by ckrgithub** [goweii/WanAndroid#20]
realm库怎样都下载不了：
![image](https://user-images.githubusercontent.com/18225851/66972853-7810c080-f0c8-11e9-9fdd-c1a348a7326b.png)

**Comment by goweii** [comment]
网络问题，你切网络试下。或者换到阿里镜像

**Comment by ckrgithub** [comment]
最近遇到网络问题，烦死人，切换阿里镜像也不行
