### ISSUE TITLE
apk1.2.2首页无法浏览CSDN的文章

### ISSUE THREAD

**Issue by DMingOu** [goweii/WanAndroid#21]
浏览文章时，发现首页无法浏览CSDN的文章，进入页面，进度条加载完成后，内容空白，而公众号，掘金，简书的文章没有问题成功显示，更换网络，测试发现，没有改变，依旧无法查看来自CSDN上的文章，望解决~

**Comment by goweii** [comment]
有没有文章的链接贴一下。
设置里配置下拦截白名单，可能没有这个域名，可以手动加下，下版本我加到默认里。

**Comment by DMingOu** [comment]
例如一篇文章https://blog.csdn.net/u014626094/article/details/83417604，无法在页面中加载出来；
在体系--导航页面--常用网站，点击标签 CSDN ，也是无法加载出页面内容；
系统设置-网页拦截，三个选项分别设置了下，问题没有解决

**Comment by goweii** [comment]
调试没有复现问题，CSDN一直在白名单的，可能是网络问题。
新版本已发，更新试下。建议卸载重装。

**Comment by goweii** [comment]
已更新x5内核，更新1.3.1版本试下

**Comment by DMingOu** [comment]
已修复无法访问CSDN的问题，感谢😄
