### ISSUE TITLE
更新后打开就提示停止运行报错

### ISSUE THREAD

**Issue by wcedla** [goweii/WanAndroid#24]
更新最新版后，包括卸载重装后都是一打开就闪退，lgg5 8.0系统

**Comment by goweii** [comment]
你更新下1.2.4，集成了BUG统计，复现下我看下日志。

**Comment by wcedla** [comment]
> 你更新下1.2.4，集成了BUG统计，复现下我看下日志。

内置的更新跳不出来，酷安更新提交一下，或者给个链接吧

**Comment by goweii** [comment]
酷安提交了，你可以在设置里面更新，首页更新一天检测一次

**Comment by wcedla** [comment]
> 酷安提交了，你可以在设置里面更新，首页更新一天检测一次

![Screenshot_2019-10-20-14-47-26](https://user-images.githubusercontent.com/16643706/67155831-dea41180-f348-11e9-93a7-adccf71d4cda.png)
![Screenshot_2019-10-20-14-47-49](https://user-images.githubusercontent.com/16643706/67155834-e2d02f00-f348-11e9-8f25-084fc80df064.png)
![Screenshot_2019-10-20-14-47-49](https://user-images.githubusercontent.com/16643706/67155836-e5cb1f80-f348-11e9-8ade-cd0b94fcc73c.png)

**Comment by wcedla** [comment]
![Screenshot_2019-10-20-14-48-00](https://user-images.githubusercontent.com/16643706/67155849-39d60400-f349-11e9-8285-718e9b8e8f48.png)

**Comment by goweii** [comment]
你加下QQ群147715512，我单发你包试下，好了我再发版。

**Comment by goweii** [comment]
已在1.2.5修复
