### ISSUE TITLE
华为p20pro 登录注册页面软键盘的打开和隐藏会遮挡按钮的小问题

### ISSUE THREAD

**Issue by mayangyang-github** [goweii/WanAndroid#29]
机型: 华为P20 pro 
登录注册页面在此机型上, 软键盘弹出和关闭有会遮挡按钮的微小的问题(对比其他机型后发现的)
录屏已经发至你的邮箱~ 希望改进下KeyboardCompat对其他机型的适配

**Comment by mayangyang-github** [comment]
华为P20 pro EMUI 9.1.0  Android 9

**Comment by goweii** [comment]
是有这个问题，周末处理

**Comment by mayangyang-github** [comment]
为什么版本升级之后在P20pro 上还是那个问题, 是没修复吗?

**Comment by goweii** [comment]
还没有修复

**Comment by yutouxiansheng** [comment]
> 为什么版本升级之后在P20pro 上还是那个问题, 是没修复吗?

你解决了吗 ？我发现确实有这个问题？华为mate10，荣耀，nova也有，

**Comment by goweii** [comment]
已修复，更新最新版
