### ISSUE TITLE
请问你底部的图片怎么制作的

### ISSUE THREAD

**Issue by GuangYiL** [goweii/WanAndroid#3]

**Comment by goweii** [comment]
底部的5个图标吗？这5个是在iconfont找的

**Comment by LannyLee** [comment]
@goweii 他说的应该是你这种高斯模糊的效果

**Comment by goweii** [comment]
这个呀，是RealtimeBlurView，可以在app的开源项目列表里看到

**Comment by LannyLee** [comment]
@goweii 你好，请问recycleview的加载动画是怎么实现的啊 ，我的是也是从右侧滑入，但是我的是整体滑入你的是单个滑入，我看了你也没有其他的处理啊

**Comment by goweii** [comment]
你搜下RecyclerView的Item Animation，我这个是用的bravh框架里封装好的，不过原理是一样的
