### ISSUE TITLE
csdn有的网页打不开

### ISSUE THREAD

**Issue by SuperMan-42** [goweii/WanAndroid#33]

**Comment by goweii** [comment]
留一下机型，sdk版本，webkit版本，网页链接
之前有人反应过这个问题，这个是个例，还没有找到怎么解决

**Comment by zqlq4ever** [comment]
不止csdn，今天的置顶标题是“利用openCV对图片处理”，“违和都在鼓吹安卓凉了”打开都有问题，opencv的打不开，安卓凉了图片无法加载，小米8，android 10

**Comment by goweii** [comment]
这个问题好像不少机型都有，也不知道是什么问题。周末换成x5内核试下。

**Comment by goweii** [comment]
已更新x5内核，更新1.3.1版本试下
