### ISSUE TITLE
大神能聊聊这个项目的设计思路吗？

### ISSUE THREAD

**Issue by MisterClown** [goweii/WanAndroid#34]
萌新一枚，对于项目里创建多个gradle文件和module文件，刚开始看的一脸懵，这样的写法有什么优势吗？

**Comment by goweii** [comment]
多个gradle是为了多module中不用每个里面都写一遍重复的配置，后面要修改也比较方便，只改一个地方就好了。多module可以更好的复用代码，方便迁移，导入下module就可以快速搭一个新项目了
