### ISSUE TITLE
最新版本的崩了，App启动不了，小米8，Android 10

### ISSUE THREAD

**Issue by zqlq4ever** [goweii/WanAndroid#36]
![Screenshot_2019-11-30-20-16-23-013_per goweii wan](https://user-images.githubusercontent.com/37474811/69900475-d6f77400-13ae-11ea-984a-7e4485323d7f.jpg)

**Comment by goweii** [comment]
一不小心就写个bug，晚上回去修复下。

**Comment by lightwind** [comment]
magic2  android10同样的问题

**Comment by goweii** [comment]
应该是都会闪退

**Comment by goweii** [comment]
已修复
