### ISSUE TITLE
大佬您这个沉浸式状态栏是在哪里设置的？

### ISSUE THREAD

**Issue by BaiMingxu** [goweii/WanAndroid#39]
看了好久没找到在哪设置的地方

**Comment by goweii** [comment]
在ActionBar里封装的：[ActionBarEx](https://github.com/goweii/ActionBarEx)

**Comment by BaiMingxu** [comment]
大佬我可以单独一个activity取消沉浸式么？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Goweii"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月26日(星期三) 下午5:16
收件人:&nbsp;"goweii/WanAndroid"<WanAndroid@noreply.github.com&gt;;
抄送:&nbsp;"michel"<806605375@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [goweii/WanAndroid] 大佬您这个沉浸式状态栏是在哪里设置的？ (#39)




在ActionBar里封装的：ActionBarEx

**Comment by goweii** [comment]
可以，有单独的属性控制，具体你看下[ActionBarEx](https://github.com/goweii/ActionBarEx)这个库

**Comment by BaiMingxu** [comment]
好的谢谢您大佬。大佬我觉得打开应用首页的时候有点慢，不知道为什么。我测了一下每次大约4秒左右。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Goweii"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月26日(星期三) 晚上6:09
收件人:&nbsp;"goweii/WanAndroid"<WanAndroid@noreply.github.com&gt;;
抄送:&nbsp;"michel"<806605375@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [goweii/WanAndroid] 大佬您这个沉浸式状态栏是在哪里设置的？ (#39)




可以，有单独的属性控制，具体你看下ActionBarEx这个库

**Comment by goweii** [comment]
是有点慢，主要影响就是在application中在mainactivity启动前强制先启动了一次webactivity页面，启动后直接关闭，所以造成首页加载延迟比较大。而这样做是因为android暗色模式在有webview时会有BUG（是不是系统BUG我不清楚），表现就是在application中初始化了为暗色模式，启动后首页是暗色模式，再打开一个有webview的页面（webactivity）返回首页，首页部分控件会刷新成亮色模式，具体原因未知，但发现可以用上面的方法避免这个问题。

**Comment by BaiMingxu** [comment]
好的，谢谢您



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Goweii"<notifications@github.com&gt;; 
发送时间: 2020年2月28日(星期五) 上午9:53
收件人: "goweii/WanAndroid"<WanAndroid@noreply.github.com&gt;; 
抄送: "michel"<806605375@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [goweii/WanAndroid] 大佬您这个沉浸式状态栏是在哪里设置的？ (#39)




是有点慢，主要影响就是在application中在mainactivity启动前强制先启动了一次webactivity页面，启动后直接关闭，所以造成首页加载延迟比较大。而这样做是因为android暗色模式在有webview时会有BUG（是不是系统BUG我不清楚），表现就是在application中初始化了为暗色模式，启动后首页是暗色模式，再打开一个有webview的页面（webactivity）返回首页，首页部分控件会刷新成亮色模式，具体原因未知，但发现可以用上面的方法避免这个问题。

**Comment by BaiMingxu** [comment]
嗷嗷，谢谢，大佬我又发现了一个小问题，不知道为什么只要一刷新首页的时候再滑动第一张banner就会滑动速度非常快，而且只是第一下这样。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Goweii"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月28日(星期五) 上午9:53
收件人:&nbsp;"goweii/WanAndroid"<WanAndroid@noreply.github.com&gt;;
抄送:&nbsp;"michel"<806605375@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [goweii/WanAndroid] 大佬您这个沉浸式状态栏是在哪里设置的？ (#39)




是有点慢，主要影响就是在application中在mainactivity启动前强制先启动了一次webactivity页面，启动后直接关闭，所以造成首页加载延迟比较大。而这样做是因为android暗色模式在有webview时会有BUG（是不是系统BUG我不清楚），表现就是在application中初始化了为暗色模式，启动后首页是暗色模式，再打开一个有webview的页面（webactivity）返回首页，首页部分控件会刷新成亮色模式，具体原因未知，但发现可以用上面的方法避免这个问题。

**Comment by goweii** [comment]
那个banner用的是个第三方库，有时间我看下为啥。

**Comment by BaiMingxu** [comment]
谢谢。我试了一下，用原声的viewpager还是有这个问题。应该不是viewpager的问题，有时间您看看，哈哈，您的库真多，太厉害了。我要多向您学习大佬。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Goweii"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月28日(星期五) 晚上7:57
收件人:&nbsp;"goweii/WanAndroid"<WanAndroid@noreply.github.com&gt;;
抄送:&nbsp;"michel"<806605375@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [goweii/WanAndroid] 大佬您这个沉浸式状态栏是在哪里设置的？ (#39)




那个banner用的是个第三方库，有时间我看下为啥。

**Comment by BaiMingxu** [comment]
大佬为什么我在微信上复制个链接，打开您的应用就会出现这个？这是怎么回事？还有我能加您一下微信或者qq么？以后k想多向您学习，如果您不方便也没关系。



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Goweii"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月28日(星期五) 晚上7:57
收件人:&nbsp;"goweii/WanAndroid"<WanAndroid@noreply.github.com&gt;;
抄送:&nbsp;"michel"<806605375@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [goweii/WanAndroid] 大佬您这个沉浸式状态栏是在哪里设置的？ (#39)




那个banner用的是个第三方库，有时间我看下为啥。

**Comment by goweii** [comment]
app关于作者里有QQ群 你可以加一下
