### ISSUE TITLE
viewpage划回来，之前的页面状态恢复问题？

### ISSUE THREAD

**Issue by eekidu** [goweii/WanAndroid#40]
`     new MultiFragmentPagerAdapter.FragmentCreator<ChapterBean, ProjectArticleFragment>() {
                    @Override
                    public ProjectArticleFragment create(ChapterBean data, int pos) {
                        return ProjectArticleFragment.create(data, pos);
                    }

                    @Override
                    public String getTitle(ChapterBean data) {
                        return data.getName();
                    }
                });`
这里的通过create形式，每次都新建Fragment。
viewpage划过去几页，再划回来，之前页的状态不会恢复（比如滑动到某一个位置）。
有什么好的办法，即不会造成内存泄漏，内存开销也能接受，实现Fragment记录状态，页面划回来时，状态恢复吗？

**Comment by goweii** [comment]
这种你可以参考一下今日头条首页的实现，为了减少内存占用，一般都是要销毁之前页面的，滚动位置和内存占用和流畅性比起来一般不重要。实在要实现恢复滚动位置，可以吧已经new过的fragment缓存起来，销毁的时候保存滚动位置到savedata中，重新创建时再取出去恢复，具体你得自己尝试下。
