### ISSUE TITLE
最新版gradle项目启动失败

### ISSUE THREAD

**Issue by BaiMingxu1** [goweii/WanAndroid#41]
AndroidStudio更新到最新版，3.6.1 gradel升级到最新。项目启动失败，报错
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/appcompat/R$drawable;
<img width="1275" alt="截屏2020-03-27 00 06 30" src="https://user-images.githubusercontent.com/24521229/77669578-f2bb0180-6fbf-11ea-8772-ebe3baed3836.png">

**Comment by goweii** [comment]
编译问题你先clean和rebuild下，不行网上查查解决办法吧
