### ISSUE TITLE
大神，萌新想问一下关于编译问题

### ISSUE THREAD

**Issue by Zhang-liangliang** [goweii/WanAndroid#42]
编译阶段无法拉取到ponyo-log-1.0.6.pom这个库，是不是local.properties配置的问题呢？

![图片1](https://user-images.githubusercontent.com/40231542/79035023-f61fd100-7bec-11ea-9a28-5ac2477a471b.png)
![图片2](https://user-images.githubusercontent.com/40231542/79035024-f7e99480-7bec-11ea-9b84-7dcc7e9e916e.png)

**Comment by goweii** [comment]
传错仓库了，把这次提交传上去了。
你把ponyo这3个依赖注释掉就好，或者回退下。这个库只是调试工具，不影响功能，暂时不开源。

**Comment by abner0914** [comment]
你好，这3个依赖注释掉以后，就无法下载ponyo这个包，但是Logutils和Utils这2个类里有使用，运行不起来，请帮忙看看，非常感谢

**Comment by goweii** [comment]
已移除Ponyo库，重新同步代码！
