### ISSUE TITLE
当前代码版本 扫一扫黑屏

### ISSUE THREAD

**Issue by Quyunshuo** [goweii/WanAndroid#44]
机型:一加5
系统版本:Android 7.1
复现逻辑:as安装应用后，打开扫一扫点击授予权限，选择始终允许，然后一直是黑屏，退出页面再次打开，会闪一下正常扫一扫的摄像页面，然后又黑屏了，退出app重新进也是如此，卸载重装也是如此，画面是黑的，扫一扫的上下动画正常，控件显示正常

**Comment by eco-ryoma** [comment]
华为P30也出现相同问题

**Comment by goweii** [comment]
是拉代码编译运行有这个问题？还是更新到最新版本也有这个问题？

**Comment by eco-ryoma** [comment]
> 是拉代码编译运行有这个问题？还是更新到最新版本也有这个问题？

这两种情况 都存在这个问题，有部分机型是正常的  例如小米9 上正常

**Comment by goweii** [comment]
好的，周末看看

**Comment by zaceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee** [comment]
红米NOTE4也出现相同问题

**Comment by goweii** [comment]
这么多机型有问题呀，扫码接的是一个第三方，抽空研究下。

**Comment by goweii** [comment]
已修复，升级1.6.0版本试下
