### ISSUE TITLE
怎么更换色彩主题

### ISSUE THREAD

**Issue by hellowolrds** [goweii/WanAndroid#47]
目前APP好像就一个主色，请问一下哈，点击不同的颜色色块切换app主题色呀，这个功能怎么实现呀。

**Comment by goweii** [comment]
Google的主题样式就可以，你可以看下Android主题和样式相关的文章。
但是大部分应用应该都是用LayoutInflater.Factory2自己实现的主题切换（有第三方）。

**Comment by hellowolrds** [comment]
没思路，楼主有什么好的demo或者第三方库可以推荐吗

**Comment by goweii** [comment]
我没有用过，你搜下很多的，原理都一样
