### ISSUE TITLE
打开简书连接 出现 net::ERRR_UNKNOWN_URLSCHEME

### ISSUE THREAD

**Issue by Q461339779** [goweii/WanAndroid#50]
修改记录  测试可行 不知道这种方式是否合适

webSetting.setUserAgentString("Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:54.0) Gecko/20100101 Firefox/54.0");

**Comment by goweii** [comment]
你贴下app版本，文章链接，必现还是偶现
