### ISSUE TITLE
作者你好 我拉了你的项目运行就闪退

### ISSUE THREAD

**Issue by JohnGreenn** [goweii/WanAndroid#51]
![image](https://user-images.githubusercontent.com/26132027/112946104-b89eb580-9167-11eb-91c5-b8bb53ad43d3.png)

**Comment by JohnGreenn** [comment]
还有这个不是最新的代码吧 落后于最新版app

**Comment by goweii** [comment]
1. 运行闪退的问题你自己调试下吧，我无法复现。
2. app最新版不开源了。
