### ISSUE TITLE
《隐私政策》中没有“file:///android_asset/privacy_policy.html”

### ISSUE THREAD

**Issue by jiyiqini** [goweii/WanAndroid#54]
项目中没有该条款文件，哦。file:///android_asset/privacy_policy.html，首次引导弹窗提示时点击《隐私政策》加载webview时，提示 net:ERR_FILE_NOT_FOUND。麻烦提交一下？

**Comment by goweii** [comment]
已修复

**Comment by jiyiqini** [comment]
> 已修复

好了。
