### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by danglu999** [goweii/WanAndroid#57]
Thanks for making this project as public.
I can not login after I type in correct username and password pair, but it works if I install the latest version by clicking the update option.

**Comment by goweii** [comment]
开源的代码里删除了自搭建的评论服务器的域名，相关的代码逻辑需要自己手动屏蔽下。

**Comment by danglu999** [comment]
你好， 开源的代码输入账号密码点击登录后无反应，但升级后可以成功登录

**Comment by goweii** [comment]
已移除评论系统
