### ISSUE TITLE
请问老哥每次下拉刷新显示不一样的古诗句是怎么做的，找了半天代码和提交都没找到😂

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [goweii/WanAndroid#58]

**Comment by goweii** [comment]
https://github.com/goweii/WanAndroid/blob/master/app/src/main/java/per/goweii/wanandroid/widget/refresh/ShiciRefreshHeader.java

**Comment by SaltedFish-Extreme** [comment]
> https://github.com/goweii/WanAndroid/blob/master/app/src/main/java/per/goweii/wanandroid/widget/refresh/ShiciRefreshHeader.java

啊，原来是这个，我开始找到了createRefreshHeader回调，但是没想到是这个类封装的，一开始还搜古诗英文，没想到直接用拼音的，没有注释太不方便了😂
