### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [goweii/WanAndroid#59]
请问是否可以将应用打包发布到 [F-Droid](https://f-droid.org)？

**Comment by goweii** [comment]
不发布了，流程太复杂，并且签名也是个问题。

**Comment by linsui** [comment]
我可以做打包提交的工作，不过签名确实是个问题。

**Comment by goweii** [comment]
那先不考虑签名问题了。你感兴趣到话可以往F-Droid提交下，我可能没空处理了。
