### ISSUE TITLE
老哥，点击文章作者这块有没有想改一改的想法？

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [goweii/WanAndroid#61]
https://github.com/hongyangAndroid/wanandroid/issues/293

**Comment by goweii** [comment]
改啥？

**Comment by SaltedFish-Extreme** [comment]
> 改啥？

🤔就是把根据作者昵称查询的文章和用户ID分享的文章都放里面啊👀

**Comment by goweii** [comment]
不改了，等鸿洋大佬改吧

**Comment by SaltedFish-Extreme** [comment]
> 不改了，等鸿洋大佬改吧

我刚才发现这个文章作者请求的两个接口，是看从文章传递过去的是作者还是分享人，有作者就没分享人，author字符串不为空，userid是-1，没有作者的话就是分享的，author是空字符串，userid的值不是-1，我用传递的userid是否为-1来判断请求哪个接口了，没问题，也可以判断author是否为空字符串，就是这俩接口的分页初始值不一样，有一个从0开始，另一个从1开始🤔
