### ISSUE TITLE
老哥，刚才搜索时候app崩溃了，日志没复制下来，光截图了，你看看吧

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [goweii/WanAndroid#62]
![微信图片_20220216205509](https://user-images.githubusercontent.com/54784104/154269101-c5a0f434-d7ca-4a47-a6a7-19dde26c679f.jpg)

**Comment by goweii** [comment]
老问题了，还没找到原因😂

**Comment by SaltedFish-Extreme** [comment]
> 老问题了，还没找到原因😂

好吧，我也不知道怎么出来的🤔

**Comment by goweii** [comment]
修复了，升级2.1.1
