### ISSUE TITLE
老哥，你网页怎么拦截那些广告的，比如简书掘金CSDN的打开app按钮链接啥的，点击直接下载app了，太恶心了😅

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [goweii/WanAndroid#63]

**Comment by goweii** [comment]
实现在.utils.web包下

**Comment by SaltedFish-Extreme** [comment]
> 实现在.utils.web包下

好的，虽然我还是看不懂😂还有，我之前拉下来kotlin版的能跑，现在拉的主分支连gradle同步都出错了😅
![image](https://user-images.githubusercontent.com/54784104/154830672-ff4b0c59-cdf8-473d-a3b6-ab7c88e33c52.png)

**Comment by goweii** [comment]
报错是不是没有签名这些配置，自己改下

**Comment by SaltedFish-Extreme** [comment]
> 报错是不是没有签名这些配置，自己改下

好像是这样，我把签名的配置都删了就没事了😂
