### ISSUE TITLE
老哥，我发现了个问题，我在另一个玩安卓app上登陆账号之后收藏或者取消文章，在这上面不会刷新，收藏图标不会改变状态，但是在这上面收藏取消在冰可乐老哥的玩安卓app上刷新就会改变，是你的收藏控件有问题还是BRVAH的item复用？

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [goweii/WanAndroid#64]

**Comment by goweii** [comment]
我试了下，都有这个问题，网站也是这样。

**Comment by goweii** [comment]
比如我打开2个浏览器，登录同一个账号，chrome里收藏一个文章，safari里刷新下还是未收藏状态。

**Comment by goweii** [comment]
[看这里](https://github.com/hongyangAndroid/wanandroid/issues/294)

**Comment by SaltedFish-Extreme** [comment]
但是老哥，冰可乐这个刷新之后就出来了，虽然刚刷新完也没有，不知道这是怎么做的
https://user-images.githubusercontent.com/54784104/155880118-a44631e7-e573-48ef-894d-39d750b5e174.mp4

https://github.com/iceCola7/WanAndroid

**Comment by goweii** [comment]
我刚也试了这个app，也是一样的问题。

**Comment by SaltedFish-Extreme** [comment]
> 我刚也试了这个app，也是一样的问题。

但是这个确实在另一个app上收藏或者取消之后，刷新后就同步状态了😂

**Comment by goweii** [comment]
![20220227_192042](https://user-images.githubusercontent.com/5456892/155880452-7322e9d3-0b7a-4284-a5f6-ec12ba791aef.gif)

**Comment by SaltedFish-Extreme** [comment]
而且除了冰可乐的，老哥你的还有鸡你太美老哥做的都是重启app或者销毁当前activity再重建之后就同步了，就比如你切换夜间模式就同步了，我怀疑是brvah框架缓存了你收藏控件状态的问题😂

**Comment by SaltedFish-Extreme** [comment]
老哥你这个怎么跟我的情况不一样的😂你是直接下载它1.1.8release版本吗

**Comment by SaltedFish-Extreme** [comment]
老哥，我总觉得我们用的不是一个版本😂

https://user-images.githubusercontent.com/54784104/155880657-9b1ec17b-22aa-42e8-9378-f292d9822547.mp4

**Comment by goweii** [comment]
> 老哥你这个怎么跟我的情况不一样的😂你是直接下载它1.1.8release版本吗

是1.1.8，看下我上面更新的gif，首页列表和我的收藏列表状态不一致，等泓洋大佬回复。

**Comment by SaltedFish-Extreme** [comment]
老哥，我试了试，在冰可乐的上面收藏或者取消收藏，在他的收藏列表是同步的，然后在你的收藏列表也是同步的😂

你的首页列表上面收藏或者取消在收藏列表也是同步的，问题就是在别的app上收藏了，你这个主页不会同步😂

https://user-images.githubusercontent.com/54784104/155880874-13c9a062-e89e-4c66-951a-48c0c0368dc7.mp4


https://user-images.githubusercontent.com/54784104/155880838-0b5ff792-9ada-4363-b6da-60248e83992c.mp4

**Comment by goweii** [comment]
鸿洋大佬已处理

**Comment by SaltedFish-Extreme** [comment]
> 鸿洋大佬已处理

好的😁
