### ISSUE TITLE
老哥，从文章打开的网页再点底下链接跳转到其他的网页，点击收藏会收藏到网址里，再打开这个跳转的网页不会显示已收藏，这个没做判断吧

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [goweii/WanAndroid#65]
我感觉这个收藏其实不大好，从一个文章页面跳转到不可预测的其他网页，收藏之后不会存储状态，当然可以从收藏的网址再打开，但是UI没有变化，多点几次也是重复收藏

我感觉只让第一次打开的文章可以收藏进文章列表，后续的网址或者其余用户自己打开的网址不给收藏就好了，要不重定向还得判断收藏状态，而且文章底下打开的网址说白了其实是站外文章，这个还得判断，加入文章的收藏列表，东西整的太多了🤔

**Comment by SaltedFish-Extreme** [comment]
所以我做玩安卓其实不想要整成浏览器的模样，就简简单单做个页面，让用户可以浏览当前文章就好了，把那些链接和跳转都屏蔽掉，省了很多工夫😄只给当前文章的网页加入收藏控件，其余网页都不显示收藏控件😂

**Comment by SaltedFish-Extreme** [comment]
但是我目前也不知道重定向跳转的网页怎么隐藏收藏控件好，比如主页置顶的扔物线文章，他就是重定向到自己博客的，把重定向的全部隐藏收藏的话，那像他这样的文章就没法收藏了，很麻烦

目前我只是把不是从文章跳转的网页隐藏收藏，这样从文章打开再跳转的网页点击收藏就没有用了，只是收藏打开的那个文章😂

**Comment by goweii** [comment]
判断当前url和初始打开的是不是一样，控制收藏的显示隐藏

**Comment by SaltedFish-Extreme** [comment]
> 判断当前url和初始打开的是不是一样，控制收藏的显示隐藏

是个办法，但是就像我说的，像首页置顶扔物线的博客，他就是打开之后重定向跳转的，打开之后也会隐藏收藏😂

**Comment by SaltedFish-Extreme** [comment]
等我一会试试效果怎么样吧，谢谢老哥了😄

**Comment by SaltedFish-Extreme** [comment]
突然发现我网页就是一个activity，收藏菜单在刚进来的时候就初始化好了，跳转链接也不会打开新网页也不会走menu的回调了😂就这样吧，把收藏功能做完就算是把这个项目做完了🤔
