### ISSUE TITLE
来自小白学习者的小建议~

### ISSUE THREAD

**Issue by FuYu520** [goweii/WanAndroid#66]
拿来学习用，这个项目是真不错，感谢作者，就是注释有点少~，对小白不太友好~

**Comment by FuYu520** [comment]
小白学习者还是先搞好基础，再慢慢上手这个项目（有一些注释这个项目就完美了）

**Comment by goweii** [comment]
等我有时间了再加加注释吧😂

**Comment by goweii** [comment]
或者你们如果愿意，可以加注释提pr过来，我来merge，一方面可以减轻我的工作量，二方面可以当做学习梳理笔记，三方面还可以成为项目贡献者，一举三得。😁

**Comment by FuYu520** [comment]
哈哈，确实加了好多注释，就是可能不是很专业的表达，到时候给大佬看看
