### ISSUE TITLE
老哥，异常处理类能打个包封装下吗，我感觉挺好的，但是不知道怎么集成进我的项目里😂

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [goweii/WanAndroid#67]

**Comment by goweii** [comment]
你是说哪里的异常处理？http还是crash？

**Comment by SaltedFish-Extreme** [comment]
> 你是说哪里的异常处理？http还是crash？

crash的

**Comment by goweii** [comment]
crash封装过了，在有个Crash类，在ponyo里面，你搜下。依赖应该在basic-utils模块。

**Comment by goweii** [comment]
不过这个之前发在gitee仓库，不知道还能拉下来不。

**Comment by SaltedFish-Extreme** [comment]
> crash封装过了，在有个Crash类，在ponyo里面，你搜下。依赖应该在basic-utils模块。

好的，麻烦老哥了，我等明天看看😘

**Comment by SaltedFish-Extreme** [comment]
> 不过这个之前发在gitee仓库，不知道还能拉下来不。

````kotlin
Crash.restartApp(applicationContext)
````
老哥，这个`Crash`类没有，github和gitee都没有ponyo仓库，我直接导入你项目里的jar包也不行😂

**Comment by SaltedFish-Extreme** [comment]
> 不过这个之前发在gitee仓库，不知道还能拉下来不。

````kotlin
Crash.restartApp(applicationContext)
````
老哥，这个`Crash`类没有，github和gitee都没有ponyo仓库，我直接导入你项目里的jar包也不行😂

**Comment by goweii** [comment]
ponyo仓库还没开源。
看下这个项目https://github.com/goweii/maven-repository.git
这个是一个maven仓库，ponyo发布到这里了。

**Comment by SaltedFish-Extreme** [comment]
> ponyo仓库还没开源。 看下这个项目https://github.com/goweii/maven-repository.git 这个是一个maven仓库，ponyo发布到这里了。

😂这个我不知道咋依赖，老哥等有空能把crash单独提取出来封装个库吗😂

**Comment by goweii** [comment]
添加上面github maven仓库源，依赖是下面这个。
per.goweii.ponyo:ponyo-crash:1.0.0

**Comment by SaltedFish-Extreme** [comment]
好的，麻烦老哥了
