### ISSUE TITLE
WebView中收藏有bug

### ISSUE THREAD

**Issue by hegaojian** [goweii/WanAndroid#7]
在首页中，部分数据在webview中收藏提示成功了，但是实际上却是没成功，在收藏列表中找不到，在项目模块中，在webview中收藏全部不成功，在列表收藏的话全部都是可以的，老哥需要检查一下webview中的收藏相关代码，测试版本：1.1.1

老哥这个项目写的确实不错啊，我现在在学习着用Kotlin写WanAndroid,用了老哥你的红心控件，和借鉴了老哥你的界面设计，哈哈，勿怪

**Comment by hegaojian** [comment]
看了一下，具体情况大概为老哥你将这些数据当成网址收藏了

**Comment by goweii** [comment]
好的，感谢反馈，回去看一下。

**Comment by goweii** [comment]
更新最新版试下1.1.3
