### ISSUE TITLE
网页暗色模式

### ISSUE THREAD

**Issue by dacaoyuan** [goweii/WanAndroid#74]

**Comment by dacaoyuan** [comment]
请问你是在哪里引用的 腾讯 X5web sdk的呢？  网页暗色模式是基于 x5web实现的吗

**Comment by goweii** [comment]
看下[WebHolder.java](https://github.com/goweii/WanAndroid/blob/master/app/src/main/java/per/goweii/wanandroid/utils/web/WebHolder.java)

**Comment by dacaoyuan** [comment]
您好，有个疑问：使用x5的 setDayOrNight(false) 夜间模式，同样的网址，我实现的效果网页是灰色背景，文字也不是白色的。您《玩安卓》app中网页效果是 黑色背景白色文字（比较符合暗黑模式效果）。请问是哪里需要做特殊设置吗？

**Comment by goweii** [comment]
黑的是android webview的效果，代码里有一段判断系统webview是否支持暗色模式的代码，支持就禁用了x5内核。
